version: "3"
services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: arm64v8/mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  redis:
    image: redis
volumes:
  mysql-data: